"""Le frasi che esistono solo dentro la finestra.

Sono quelle che al terminale non servirebbero a niente: i nomi delle quattro
voci del menu, i titoli e le descrizioni delle sezioni, le etichette di campi
che a riga di comando sono argomenti. Stanno separate dai quattro cataloghi dei
mestieri per questo, non perche' riguardino un programma diverso.

Qui dentro non c'e' markup di Rich: nessuna di queste frasi passa da una
console.
"""
from __future__ import annotations

# ── Testi propri dell'interfaccia ────────────────────────────────────────────
# Non stanno in server/ perche' riguardano solo questa finestra, e mescolarli
# al catalogo di AudioDex renderebbe piu' difficile capire, leggendo quel file,
# quali frasi appaiono a terminale e quali no.
TESTI: dict[str, str] = {
    'app.apri_risultati': 'Apri la cartella dei risultati',
    'menu.audio':       'Audio',
    'menu.burn':        'Masterizzazione',
    'menu.pix':         'Rimasterizza',
    'menu.clip':        'Montaggio',
    'menu.soon':        'in arrivo',
    'audio.title':      'Scarica da YouTube',
    'audio.desc':       'Incolla un link, o cerca per nome. Playlist e album interi '
                        'finiscono in una cartella ordinata.',
    'audio.mode':       'Come cerco',
    'audio.mode.url':   'Ho un link',
    'audio.mode.search': 'Cerca per nome',
    'audio.input.url':  'Link del video, della playlist o dell\'album',
    'audio.input.search': 'Nome del brano o dell\'artista',
    'audio.format':     'Formato',
    'audio.media':      'Cosa scarico',
    'audio.media.audio': 'Solo audio',
    'audio.media.video': 'Video intero',
    'audio.workers':    'Download in parallelo',
    'audio.lyrics':     'Cerca i testi sincronizzati su LRCLIB',
    'audio.split':      'Dividi in tracce gli album caricati come video unico',
    'audio.analyze':    'Guarda cosa c\'è',
    'audio.start':      'Scarica',
    'audio.results':    'Cosa ho trovato',
    'audio.results.empty': 'Incolla un link e premi «Guarda cosa c\'è».',
    'targhetta.lavora': 'in corso',
    'targhetta.guasto': 'errore',
    'comune.chiudi':    'Ho capito',
    'status.idle':      'In attesa',
    'status.working':   'In corso',
    'status.done':      'Fatto',
    'status.error':     'Errore',
    'err.no_input':     'Prima incolla un link o scrivi cosa cercare.',
    'err.nothing':      'Non ho trovato niente.',
    'err.busy':         'C\'è già qualcosa in corso.',
    'res.playlist':     '{n} brani  ·  {titolo}',
    'res.single':       'Un video  ·  {titolo}',
    'res.search':       '{n} risultati',
    'sel.all':          'Tutti',
    'sel.none':         'Nessuno',
    'sel.count':        '{n} scelti',
    'fase.attesa':      'in coda',
    'fase.download':    'scarico',
    'fase.convert':     'converto',
    'fase.lyrics':      'cerco il testo',
    'fase.tag':         'scrivo i tag',
    'fase.ok':          'fatto',
    'fase.skip':        'c\'era già',
    'fase.fail':        'fallito',
    'lavoro.avanzo':    '{fatte} di {totale}',
    'scorciatoie':      'Invio per cercare  ·  Ctrl+Invio per scaricare',
    'trascina':         'Lascia qui il link',
    'err.no_file':      'Prima scegli un file.',
    'comune.sfoglia':   'Sfoglia',

    # ── Masterizzazione ──────────────────────────────────────────────────────
    'burn.title':       'Masterizza un CD audio',
    'burn.desc':        'Trasforma una cartella di brani in un CD vero, di quelli che '
                        'legge qualunque autoradio. Su un CD-R non si torna indietro.',
    'burn.folder':      'Cartella dei brani',
    'burn.scan':        'Leggi la cartella',
    'burn.start':       'Masterizza',
    'burn.speed':       'Velocità',
    'burn.speed.auto':  'Automatica',
    'burn.drive':       'Unità',
    'burn.drive.auto':  'La prima libera',
    'burn.dry':         'Prova senza incidere: verifica tutto e non tocca il disco',
    'burn.noeject':     'Non espellere il disco alla fine',
    'burn.level':       'Livella il volume fra le tracce',
    'burn.trim':        'Rifila i silenzi a inizio e fine traccia',
    'burn.tracks':      'Scaletta',
    'burn.empty':       'Scegli una cartella e premi «Leggi la cartella».',
    'burn.capacity':    '{minuti} di {limite} minuti',
    'burn.over':        'Non ci sta: togli qualche traccia',
    'burn.order':       'Ordine: {criterio}  ·  trascina per cambiarlo',
    'burn.no_folder':   'Quella cartella non esiste.',
    'burn.no_audio':    'Nessun file audio in quella cartella.',
    'burn.no_pywin32':  'Manca pywin32: pip install pywin32',
    'burn.no_drive':    'Nessun masterizzatore collegato.',
    'burn.only_windows': 'La masterizzazione funziona solo su Windows.',
    'burn.reordered':   'Ordine cambiato: preparo la scaletta.',

    # ── Rimasterizzazione ────────────────────────────────────────────────────
    'pix.title':        'Rimasterizza un video',
    'pix.desc':         'Toglie i difetti della compressione e ingrandisce. Non inventa '
                        'dettaglio: lavora in sottrazione.',
    'pix.file':         'Video da rimasterizzare',
    'pix.analyze':      'Analizza',
    'pix.start':        'Rimasterizza',
    'pix.diagnosis':    'Diagnosi',
    'pix.empty':        "Scegli un video e premi «Analizza»: qui compare cosa c'è da sistemare.",
    'pix.preset':       'Trattamento',
    'pix.preset.auto':  'Dalla diagnosi',
    'pix.resolution':   "Risoluzione d'arrivo",
    'pix.suggested':    'consigliata',
    'pix.gpu':          'Codifica sulla GPU: più veloce, ma rimette parte dei quadretti',
    'pix.compare':      'Salva il confronto prima/dopo',
    'pix.preview':      'Prima e dopo',
    'pix.preview.empty': 'A lavoro finito compare qui, a sinistra il file di partenza.',
    'pix.unreadable':   'Nessun flusso video leggibile in quel file.',
    'pix.done':         'Fatto: {file}',
    'pix.failed':       'La rimasterizzazione non è riuscita.',

    # ── Montaggio ────────────────────────────────────────────────────────────
    'clip.title':       'Monta e converti',
    'clip.desc':        'Sei operazioni. Dove può, copia invece di ricodificare: '
                        'costa secondi e non perde un bit.',
    'clip.op':          'Operazione',
    'clip.file':        'File di partenza',
    'clip.files':       "File da unire, nell'ordine",
    'clip.start':       'Esegui',
    'clip.from':        'Da',
    'clip.to':          'A',
    'clip.duration':    'Durata',
    'clip.preciso':     'Taglio preciso al fotogramma (ricodifica, molto più lento)',
    'clip.capitoli':    'Un capitolo per ogni file unito',
    'clip.grid':        'Griglia',
    'clip.result':      'Risultato',
    'clip.result.empty': "Qui compare ciò che esce dall'operazione.",
    'clip.need_two':    'Per unire servono almeno due file.',
    'clip.done':        'Fatto: {file}',
    'clip.failed':      'Non è riuscita: {file}',
    'clip.op.taglia':   'Taglia uno spezzone',
    'clip.op.unisci':   'Unisci più file',
    'clip.op.gif':      'Ricava una GIF',
    'clip.op.webp':     'Ricava un WebP (nove volte più leggero)',
    'clip.op.provino':  'Provino a griglia',
    'clip.op.compat':   'Rendi leggibile da apparecchi datati',
    'done.summary':     'Scaricati {ok} su {tot}  ·  {falliti} falliti',
}
